#!/bin/bash
BIN_PATH=`dirname "$0"`
cd $BIN_PATH



mkdir -p src/test/generated/org/capnproto/test

capnp compile -I ../compiler/src/main/schema/  --src-prefix=src/test/schema/ -o../capnpc-java:src/test/generated/org/capnproto/test src/test/schema/*.capnp

